### ISSUE TITLE
[Tracking] rustdocs for public functions of libazureinit

### ISSUE THREAD

**Issue by dongsupark** [Azure/azure-init#127]
## Description

Public functions/structs/variables of libazureinit should have own [rustdocs](https://doc.rust-lang.org/rustdoc/index.html). Ideally they should also include example code.

 - [distro](https://github.com/Azure/azure-init/blob/main/libazureinit/src/distro.rs)
   - [ ] /create_user_with_useradd
   - [ ] set_password_with_passwd
   - [ ] set_hostname_with_hostnamectl
 - [error](https://github.com/Azure/azure-init/blob/main/libazureinit/src/error.rs)
   - [ ] Error
 - [goalstate](https://github.com/Azure/azure-init/blob/main/libazureinit/src/goalstate.rs)
   - [ ] Goalstate
   - [ ] Container
   - [ ] RoleInstanceList
   - [ ] RoleInstance
   - [ ] get_goalstate
   - [ ] report_health

 - [http](https://github.com/Azure/azure-init/blob/main/libazureinit/src/http.rs)
   - [x] RETRY_CODES
   - [x] HARDFAIL_CODES
   - [ ] IMDS_HTTP_TIMEOUT_SEC
   - [ ] WIRESERVER_HTTP_TIMEOUT_SEC

 - [imds](https://github.com/Azure/azure-init/blob/main/libazureinit/src/imds.rs)/
   - [ ] InstanceMetadata
   - [x] Compute
   - [x] OsProfile
   - [x] PublicKeys
   - [x] string_bool
   - [ ] query

 - [media](https://github.com/Azure/azure-init/blob/main/libazureinit/src/media.rs)
   - [ ] Environment
   - [ ] ProvisioningSection
   - [ ] LinuxProvisioningConfigurationSet
   - [ ] PlatformSettingsSection
   - [ ] PlatformSettings
   - [ ] PATH_MOUNT_DEVICE
   - [ ] PATH_MOUNT_POINT
   - [ ] get_mount_device
   - [ ] Mounted
   - [ ] Unmounted
   - [ ] Media
   - [ ] parse_ovf_env
   - [ ] mount_parse_ovf_env

 - [provision/hostname](https://github.com/Azure/azure-init/blob/main/libazureinit/src/provision/hostname.rs)
   - [x] Provisioner

 - [provision/mod](https://github.com/Azure/azure-init/blob/main/libazureinit/src/provision/mod.rs)
   - [x] Provision
   - [x] Provision::hostname_provisioners
   - [x] Provision::user_provisioners
   - [x] Provision::password_provisioners
   - [x] Provision::provision

 - [provision/password](https://github.com/Azure/azure-init/blob/main/libazureinit/src/provision/password.rs)
   - [x] Provisioner

 - [provision/ssh](https://github.com/Azure/azure-init/blob/main/libazureinit/src/provision/ssh.rs)
   - [ ] provision_ssh

 - [provision/user](https://github.com/Azure/azure-init/blob/main/libazureinit/src/provision/user.rs)
   - [x] User
   - [x] User::new
   - [x] User::with_password
   - [x] User::with_groups
   - [x] Provisioner
   - [ ] Provisioner::create

 - [unittest](https://github.com/Azure/azure-init/blob/main/libazureinit/src/unittest.rs)
   - [ ] get_http_response_payload
   - [ ] serve_requests

**Comment by John15321** [comment]
https://github.com/Azure/azure-init/pull/147

Here is a PR (a draft, but soon ready) for the ssh.rs module @dongsupark
