### ISSUE TITLE
[RFE] consumable library for integration with other provisioning agents

### ISSUE THREAD

**Issue by t-lo** [Azure/azure-init#33]
## Current situation

The provisioning agent implements all features in a single application.

## Impact

Re-using the agent's functionality from other agents like e.g. [Afterburn](https://github.com/coreos/afterburn) is challenging.
This impacts adoption of the agent by the larger Linux ecosystem and hinders its mission of being a reference implementation for a minimal Azure provisioning guest agent.

## Ideal future situation

- [x] The provisioning agent provides a library (rust crate) which is consumable by other projects. (https://github.com/Azure/azure-init/pull/39)
- [x] The library is built and tested in CI, versioned releases are published regularly.

## Follow-up tasks

- [ ] The library is integrated with Afterburn (possibly in a WIP fork).
- [ ] Afterburn using the library is integrated with Flatcar to move away from wa-agent supplied guest configuration.
- [ ] Extended Afterburn support of Azure using the library is contributed upstream.

**Comment by dongsupark** [comment]
Published v0.1.1 of [libazureinit](https://crates.io/crates/libazureinit) and [azure-init](https://crates.io/crates/azure-init).
The 2nd one, `The library is built and tested in CI, versioned releases are published regularly` is done.
